// This file is auto-generated by gomobile. Do not edit.
// Package whatsapp provides a Go bridge to WhatsApp Web/linked-device protocol.
// It exposes a stable interface to Kotlin via gomobile AAR.

package whatsapp

// Native types (stubs for gomobile binding)

type ConnectionState int

const (
    Disconnected ConnectionState = iota
    Pairing
    Connected
    Connecting
    Error
    LoggedOut
    SessionExpired
)
